export enum Sexuality {
  Allosexual = "Allosexual",
  Homosexual = "Homosexual",
  Heterosexual = "Heterosexual",
  Bisexual = "Bisexual",
  Asexual = "Asexual",
  Apothisexual = "Apothisexual",
  Pansexual = "Pansexual",
  Autochorisexual = "Autochorisexual",
  Cupiosexual = "Cupiosexual",
  GrayAsexual = "Gray Asexual",
  Lithosexual = "Lithosexual/Akoisexual",
  Demisexual = "Demisexual",
  Fraysexual = "Fraysexual",
}
