version: 2.1

jobs:
  lint_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test
  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - run: npm install
      - run: npm run build
      - run: aws s3 sync ./dist s3://$S3_BUCKET --delete
      - run: AWS_PAGER="" aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST --paths "/*"

workflows:
  deploy_lint_and_test:
    jobs:
      - lint_test
      - deploy:
          filters:
            branches:
              only:
                - base
          requires:
            - lint_test
